fix: use dynamic arch for opentofu binary downloads
thegeeklab/wp-opentofu pull request #122
Opened 2024-12-02 21:32 UTC by pat-s

2024-12-02 21:38 UTC, xoxys requested changes

2024-12-02 21:38 UTC, xoxys commented on Containerfile.multiarch
> +    ARCH=$(apk --print-arch | sed 's/x86_64/amd64/; s/aarch64/arm64/') && \
Good catch. Please utilize `TARGETARCH` see https://gitea.rknet.org/container/alpine-tools/src/branch/main/Containerfile.multiarch#L39

2024-12-02 22:10 UTC, xoxys approved these changes

2024-12-02 22:10 UTC, merged

2024-12-02 22:10 UTC, xoxys commented
Thanks!

2024-12-03 08:35 UTC, pat-s commented
A new release would be appreciated 💙️

2024-12-03 09:43 UTC, xoxys commented
Sure. Release triggered.